### ISSUE TITLE
Caddy2 使用 Cloudflare DNS 插件后，webhook 未能生效

### ISSUE THREAD

**Issue by allanpk716** [WingLim/caddy-webhook#1]
按照你的博客给的步骤，改动是使用了 Cloudflare  DNS 插件，折腾了下，github 触发 webhook 无法访问 ，提示403。

Cloudflare  DNS 用于其他的网站是正常工作的。

配置如下：

```
xxx.xyz {
  tls {
      dns cloudflare 123456
  }  
  encode gzip
  root * /data/www/blog
  file_server
  
  handle_errors {
  	@404 {
  		expression {http.error.status_code} == 404
  	}
  	handle @404 {
  		rewrite * /404.html
  		file_server
  	}
  }
  route /webhook {
    webhook {
      repo https://github.com/allanpk716/allanpk716.github.io.git
      branch main
      path /data/www/blog
      secret xxxxx
    }
  }
}
```

**Comment by WingLim** [comment]
能贴一下日志么？

**Comment by allanpk716** [comment]
> 能贴一下日志么？

## 截图
![image](https://user-images.githubusercontent.com/1176000/131061915-d9e34dad-5327-4734-95b3-51eff429752f.png)

## 日志详情
```
Alt-Svc: h3-27=&quot;:443&quot;; ma=86400, h3-28=&quot;:443&quot;; ma=86400, h3-29=&quot;:443&quot;; ma=86400, h3=&quot;:443&quot;; ma=86400
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Ray: 685192c6f8975b23-IAD
Content-Length: 16
Content-Type: text/plain; charset=UTF-8
Date: Fri, 27 Aug 2021 01:37:12 GMT
Expect-Ct: max-age=604800, report-uri=&quot;https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct&quot;
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Nel: {&quot;success_fraction&quot;:0,&quot;report_to&quot;:&quot;cf-nel&quot;,&quot;max_age&quot;:604800}
Report-To: {&quot;endpoints&quot;:[{&quot;url&quot;:&quot;https:\/\/a.nel.cloudflare.com\/report\/v3?s=VeN7JUhkpCKT246ypUuCIhSTsGreM8pX6bwiEkU5wlC0xMoCC8OfTZg9dfJ0RkSnmomkDs3wc6pEjEXIqim3cw1ozA9Yec2H3kUhUnXdxk0aeTrql4x%2Bn%2BV5eQ%3D%3D&quot;}],&quot;group&quot;:&quot;cf-nel&quot;,&quot;max_age&quot;:604800}
Server: cloudflare
X-Frame-Options: SAMEORIGIN
```

**Comment by allanpk716** [comment]
刚才尝试去掉 cloudflare  dns ，直接域名指向是服务器真实地址，配置的 tls 修改为

`tls xxx@gmail.com`

返回的截图如下

![image](https://user-images.githubusercontent.com/1176000/131062228-11e231ae-a655-4451-9879-258ee870d4d2.png)

DNS 我查询了，是生效了的。

**Comment by WingLim** [comment]
能再贴下caddy的日志么

**Comment by allanpk716** [comment]
> 能再贴下caddy的日志么

没看到生成日志。你的这个插件生效与否怎么能看出来呢？我是在官网勾选多个插件的形式下载使用的。

**Comment by WingLim** [comment]
参考：https://caddyserver.com/docs/caddyfile/directives/log
可以在 `Caddyfile` 中添加

```
log {
  output stdout
}
```

使用 `caddy list-modules` 命令可以查看 `caddy` 的二进制文件中包含的 modules

生效了的话，webhook 模块会在日志中输出

**Comment by allanpk716** [comment]
> 参考：https://caddyserver.com/docs/caddyfile/directives/log
> 可以在 `Caddyfile` 中添加
> 
> ```
> log {
>   output stdout
> }
> ```
> 
> 使用 `caddy list-modules` 命令可以查看 `caddy` 的二进制文件中包含的 modules
> 
> 生效了的话，webhook 模块会在日志中输出

日志已经启用了，module 也是有的。还有什么可能导致无法使用吗？日志依然没有生成。

## 配置

```
xxx.xyz {
  tls xxx@gmail.com
  encode gzip
  log {
    output file /var/log/access.log
  }
  root * /data/www/blog
  file_server
  
  handle_errors {
  	@404 {
  		expression {http.error.status_code} == 404
  	}
  	handle @404 {
  		rewrite * /404.html
  		file_server
  	}
  }
  route /webhook {
    webhook {
      repo https://github.com/allanpk716/allanpk716.github.io.git
      branch main
      path /data/www/blog
      secret xxx
    }
  }
}
```

## module list 
![image](https://user-images.githubusercontent.com/1176000/131068591-4b48200a-7096-4994-b674-08804bd1e19c.png)

**Comment by WingLim** [comment]
你试试用 `caddy run --config Caddyfile --adapter caddyfile` 来运行，终端应该会有日志。

**Comment by allanpk716** [comment]
> adapter

谢谢。看到的日志如下：

## 日志
![image](https://user-images.githubusercontent.com/1176000/131069509-5f2f2489-d429-44cb-b92b-49a58880257d.png)


但是里面提及的 invalid character 'p'  这个没看到配置文件有单独写的。

**Comment by WingLim** [comment]
我在 caddyserver.com 上下了个二进制包试了试是正常的哎，我研究研究

**Comment by allanpk716** [comment]
> 我在 caddyserver.com 上下了个二进制包试了试是正常的哎，我研究研究

麻烦你啦

**Comment by WingLim** [comment]
我本地跑了跑你的 `Caddyfile`，没有问题哎，你用的是什么系统？Windows么？

**Comment by allanpk716** [comment]
> 我本地跑了跑你的 `Caddyfile`，没有问题哎，你用的是什么系统？Windows么？

搬瓦工的 CenterOS...

**Comment by allanpk716** [comment]
> 我本地跑了跑你的 `Caddyfile`，没有问题哎，你用的是什么系统？Windows么？

原因找到了，我这里是使用 systemctl 启动 sevice 来完成的，里面指定的是 caddy 用户和组，他们权限不够导致的。包括日志没有写出来也是这个原因，但是没有相应的 Error 挺奇怪的。谢啦。

**Comment by allanpk716** [comment]
如果不使用 cloudflare 的 DNS（代理 CDN 加速） 功能，直连服务器是可以正常使用了。但是如果开启了 cloudflare 的 CDN 加速功能，则有以下的故障提示。

## Caddy 日志
![image](https://user-images.githubusercontent.com/1176000/131245626-94adc3bb-aa21-4953-97ac-200a0bce024d.png)

配置信息还是参考你之前的文章，没有更改。从 hugo 分支编译推送到 main 分支

**Comment by WingLim** [comment]
噢，因为 GitHub 的 webhook 配置是所有的分支的推送都会触发 webhook，所以这里是正常的
也就是说：
1. push 文件到 hugo 分支后，会触发 webhook，但模块判断不是配置文件设置的分支，会报错
2. github action 自动构建博客并推送到 main 分支，会触发 webhook，然后模块拉取最新的文件

第一个 webhook 请求会导致报错，第二个 webhook 请求就会正常工作了

这个是因为 GitHub 的 webhook 触发机制导致的

然后在这个日志后面有没有 `updating repository` 的日志呢？

**Comment by WingLim** [comment]
我后面改一改让它报 Warn 而不是 Error

**Comment by allanpk716** [comment]
`updating repository` 是执行了的，但是 Github 的 Webhook 会提示异常，还以为故障了。

**Comment by WingLim** [comment]
> `updating repository` 是执行了的，但是 Github 的 Webhook 会提示异常，还以为故障了。

好的，这个应该报 Warning，而不是 Error，当时为了偷懒，就没区分，会尽快修改
