### ISSUE TITLE
ERROR	http.handlers.webhook	repository not setup	{"error": "worktree contains unstaged changes", "path": "/usr/share/caddy/myblog"}

### ISSUE THREAD

**Issue by flypolarbear** [WingLim/caddy-webhook#2]
The above error occurs when I the GIT Hugo project folder. After testing , only the index.html file can be modified freely.An error will be reported whenever the folder is first seen . Did git make a distinction. thanks for your surport.

**Comment by WingLim** [comment]
Can you describe what did you do in you blog repo?

The module is using for sync the remote/upstream repo from github, gitlab or some website else.

This error means you edit files in local machine repo, but did not stage them.

**Comment by flypolarbear** [comment]
thx for for your reply. I used to synchronize the whole project, Want to record changes across Hugo. However, I encountered the above error. I think it may be that I put the project in the static directory of caddy, and it should not be stored there, so I can't find the index file at the first time.Now I only synchronize the public folder, The problem is solved.
